import type { Metadata, Viewport } from 'next';

export const metadata: Metadata = {
  title: 'auth page',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex w-full flex-col justify-center space-y-2">
      {children}
    </div>
  );
}
